# Generated by Django 4.1.1 on 2023-02-12 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0028_moneydeleting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField(default=1, verbose_name='رقم المستوى')),
                ('content', models.CharField(max_length=1023, verbose_name='المحتوى')),
                ('is_passed', models.BooleanField(default=False, verbose_name='تم إنهاؤه')),
            ],
            options={
                'verbose_name': 'مستوى',
                'verbose_name_plural': 'المستويات',
            },
        ),
        migrations.CreateModel(
            name='Specializtion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=511, verbose_name='الاسم')),
                ('students', models.ManyToManyField(to='main_app.student', verbose_name='الطلاب')),
            ],
            options={
                'verbose_name': 'اختصاص',
                'verbose_name_plural': 'الاختصاصات',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_start', models.IntegerField(verbose_name='بداية القسم')),
                ('part_end', models.IntegerField(verbose_name='نهاية القسم')),
                ('part_number', models.IntegerField(default=1, verbose_name='رقم القسم')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specializtions.level', verbose_name='المستوى')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'أقسام',
            },
        ),
        migrations.AddField(
            model_name='level',
            name='specializtion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specializtions.specializtion', verbose_name='الاختصاص'),
        ),
    ]
