# Generated by Django 4.1.1 on 2023-02-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_moneydeleting'),
        ('specializtions', '0002_alter_specializtion_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='is_passed',
        ),
        migrations.RemoveField(
            model_name='specializtion',
            name='students',
        ),
        migrations.AddField(
            model_name='part',
            name='students',
            field=models.ManyToManyField(blank=True, to='main_app.student', verbose_name='الطلاب'),
        ),
    ]
