# Generated by Django 4.1.1 on 2023-02-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_moneydeleting'),
        ('specializtions', '0003_remove_level_is_passed_remove_specializtion_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='students',
            field=models.ManyToManyField(blank=True, to='main_app.student', verbose_name='الطلاب الذين أنهوا القسم'),
        ),
    ]
