# Generated by Django 4.1.1 on 2023-02-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specializtions', '0004_alter_part_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part_number',
            field=models.IntegerField(default=1, verbose_name='ترتيب القسم'),
        ),
    ]
