# Generated by Django 4.1.1 on 2022-10-08 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0004_memorizemessage_student_string_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="memorizenotes",
            name="updated_at",
        ),
    ]
