# Generated by Django 4.1.1 on 2022-10-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0008_coming"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coming",
            name="coming_type",
        ),
        migrations.RemoveField(
            model_name="coming",
            name="is_late",
        ),
        migrations.AddField(
            model_name="coming",
            name="points",
            field=models.IntegerField(default=0, verbose_name="نقاط الحضور"),
        ),
    ]
