# Generated by Django 4.1.1 on 2022-10-25 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_comingcategory_coming_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coming',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.comingcategory', verbose_name='نوع الحضور'),
        ),
    ]
