# Generated by Django 4.1.1 on 2022-10-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0011_alter_coming_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="coming",
            name="note",
            field=models.TextField(blank=True, null=True, verbose_name="ملاحظة"),
        ),
    ]
