# Generated by Django 4.1.1 on 2022-10-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_coming_registered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_q_test_certificate',
            field=models.BooleanField(default=True, verbose_name='هل يوجد شهادة سبر'),
        ),
    ]
