# Generated by Django 4.1.1 on 2022-11-01 13:16

from django.db import migrations, models
from main_app.default_json import json_default_value_three


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0014_alter_student_is_q_test_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="q_awqaf_test",
            field=models.JSONField(
                default=json_default_value_three,
                verbose_name="سبر القرآن في الأوقاف",
            ),
        ),
    ]
