# Generated by Django 4.1.1 on 2022-11-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0016_controlsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controlsettings",
            name="double_points",
            field=models.BooleanField(default=False, verbose_name="مضاعفة النقاط"),
        ),
        migrations.AlterField(
            model_name="controlsettings",
            name="point_value",
            field=models.IntegerField(verbose_name="قيمة النقطة"),
        ),
    ]
