# Generated by Django 4.1.1 on 2022-11-01 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0017_alter_controlsettings_double_points_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoublePointMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sended_at", models.DateTimeField(auto_now_add=True)),
                ("point", models.IntegerField()),
                ("content", models.JSONField(default=dict)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main_app.student",
                        verbose_name="الطالب",
                    ),
                ),
            ],
            options={
                "verbose_name": "رسالة مضاعفة",
                "verbose_name_plural": "رسائل مضاعفة",
            },
        ),
    ]
