# Generated by Django 4.1.1 on 2022-11-01 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0018_doublepointmessage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doublepointmessage",
            old_name="point",
            new_name="points",
        ),
    ]
