# Generated by Django 4.1.1 on 2022-11-02 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0020_doublepointmessage_memorize_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doublepointmessage",
            name="memorize_message",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main_app.memorizemessage",
                verbose_name="رسالة التسميع",
            ),
        ),
    ]
