# Generated by Django 3.2.13 on 2022-11-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0021_alter_doublepointmessage_memorize_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="doublepointmessage",
            name="message_type",
            field=models.IntegerField(choices=[(1, "تسميع"), (2, "سبر")], default=1),
        ),
    ]
