# Generated by Django 4.1.1 on 2023-02-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_moneydeleting'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneydeleting',
            name='active_to_points',
            field=models.BooleanField(default=False, verbose_name='مخصومة من النقاط'),
        ),
    ]
