# Generated by Django 4.1.1 on 2023-02-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0029_moneydeleting_active_to_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moneydeleting",
            name="active_to_points",
            field=models.BooleanField(default=True, verbose_name="مخصومة من النقاط"),
        ),
    ]
