# Generated by Django 4.1.1 on 2023-08-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0033_awqaftestnoq_awqafnoqstudentrelation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="q_test_candidate",
        ),
        migrations.AlterField(
            model_name="memorizemessage",
            name="message_type",
            field=models.IntegerField(
                choices=[(1, "تسميع"), (2, "سبر")],
                default=1,
                verbose_name="نوع الرسالة",
            ),
        ),
    ]
