# Generated by Django 4.1.1 on 2023-08-18 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0035_remove_coming_note"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PointsDeleting",
        ),
        migrations.DeleteModel(
            name="PointsDeletingCause",
        ),
    ]
