# Generated by Django 4.1.1 on 2023-08-31 15:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0038_alter_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="alarbaein_alnawawia_new",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="الأربعين النووية جديد",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="alarbaein_alnawawia_old",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="الأربعين النووية قديم",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="allah_names",
            field=models.BooleanField(default=False, verbose_name="أسماء الله الحسنى"),
        ),
        migrations.AddField(
            model_name="student",
            name="riad_alsaalihin_new",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="رياض الصالحين جديد",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="riad_alsaalihin_old",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="رياض الصالحين قديم",
            ),
        ),
        migrations.AlterField(
            model_name="doublepointmessage",
            name="message_type",
            field=models.IntegerField(
                choices=[
                    (1, "تسميع"),
                    (2, "سبر"),
                    (3, "أربعين نووية"),
                    (4, "رياض الصالحين"),
                    (5, "أسماء الله الحسنى"),
                ],
                default=1,
                verbose_name="نوع التسميع",
            ),
        ),
        migrations.AlterField(
            model_name="memorizemessage",
            name="message_type",
            field=models.IntegerField(
                choices=[
                    (1, "تسميع"),
                    (2, "سبر"),
                    (3, "أربعين نووية"),
                    (4, "رياض الصالحين"),
                    (5, "أسماء الله الحسنى"),
                ],
                default=1,
                verbose_name="نوع الرسالة",
            ),
        ),
    ]
