# Generated by Django 4.1.1 on 2023-08-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0039_student_alarbaein_alnawawia_new_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="allah_names",
        ),
        migrations.AddField(
            model_name="student",
            name="allah_names_new",
            field=models.BooleanField(
                default=False, verbose_name="أسماء الله الحسنى جديد"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="allah_names_old",
            field=models.BooleanField(
                default=False, verbose_name="أسماء الله الحسنى قديم"
            ),
        ),
    ]
