# Generated by Django 4.1.1 on 2023-09-08 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0042_alter_doublepointmessage_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="is_q_test_certificate",
        ),
    ]
