# Generated by Django 4.1.1 on 2023-09-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0043_remove_student_is_q_test_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="controlsettings",
            name="hidden_ids",
            field=models.JSONField(default=list, verbose_name="المعرفات المخفية"),
        ),
    ]
