# Generated by Django 4.1.1 on 2023-09-19 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0044_controlsettings_hidden_ids"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="الاسم"),
                ),
            ],
            options={
                "verbose_name": "المجموعة",
                "verbose_name_plural": "المجموعات",
            },
        ),
        migrations.AddField(
            model_name="student",
            name="student_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main_app.studentgroup",
                verbose_name="مجموعة الطالب",
            ),
        ),
    ]
