# Generated by Django 4.1.1 on 2023-09-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0047_alter_comingcategory_options_remove_coming_points_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="parts_received",
            field=models.CharField(
                default="", max_length=255, verbose_name="الأجزاء المستلمة"
            ),
        ),
    ]
