# Generated by Django 4.1.1 on 2023-09-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0048_student_parts_received"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="parts_received",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="الأجزاء المستلمة"
            ),
        ),
    ]
