# Generated by Django 4.1.1 on 2023-09-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0049_alter_student_parts_received"),
    ]

    operations = [
        migrations.AddField(
            model_name="controlsettings",
            name="event_title",
            field=models.CharField(
                max_length=511, null=True, verbose_name="عنوان الحدث"
            ),
        ),
    ]
