# Generated by Django 4.2.6 on 2023-10-18 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0050_controlsettings_event_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coming',
            old_name='master_name',
            new_name='master',
        ),
        migrations.RenameField(
            model_name='memorizemessage',
            old_name='master_name',
            new_name='master',
        ),
        migrations.RenameField(
            model_name='memorizenotes',
            old_name='master_name',
            new_name='master',
        ),
        migrations.RenameField(
            model_name='pointsadding',
            old_name='master_name',
            new_name='master',
        ),
    ]
