# Generated by Django 4.2.6 on 2023-12-25 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0053_remove_awqafnoqstudentrelation_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'فئة ملفات',
                'verbose_name_plural': 'فئات الملفات',
            },
        ),
        migrations.CreateModel(
            name='AssetFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='assets')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.assetscategory')),
            ],
            options={
                'verbose_name': 'ملف للتحميل',
                'verbose_name_plural': 'ملفات للتحميل',
            },
        ),
    ]
