# Generated by Django 4.2.6 on 2023-12-25 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0054_assetscategory_assetfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetfile',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.assetscategory', verbose_name='الفئة'),
        ),
        migrations.AlterField(
            model_name='assetfile',
            name='file',
            field=models.FileField(upload_to='assets', verbose_name='الملف'),
        ),
        migrations.AlterField(
            model_name='assetfile',
            name='name',
            field=models.CharField(max_length=255, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='assetscategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='الاسم'),
        ),
    ]
