# Generated by Django 4.2.6 on 2024-05-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0056_newstudent_student_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstudent',
            name='student_class',
            field=models.CharField(choices=[('ثاني', 'ثاني'), ('ثالث', 'ثالث'), ('رابع', 'رابع'), ('خامس', 'خامس'), ('سادس', 'سادس'), ('سابع', 'سابع'), ('ثامن', 'ثامن'), ('عاشر', 'عاشر'), ('حادي عشر', 'حادي عشر'), ('بكالوريا', 'بكالوريا')], default='ثاني', max_length=20),
            preserve_default=False,
        ),
    ]
