# Generated by Django 4.2.6 on 2024-09-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0057_newstudent_student_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstudent',
            name='student_class',
            field=models.CharField(choices=[('ثاني', 'ثاني'), ('ثالث', 'ثالث'), ('رابع', 'رابع'), ('خامس', 'خامس'), ('سادس', 'سادس'), ('سابع', 'سابع'), ('ثامن', 'ثامن'), ('تاسع', 'تاسع'), ('عاشر', 'عاشر'), ('حادي عشر', 'حادي عشر'), ('بكالوريا', 'بكالوريا')], max_length=20, verbose_name='الصف الدراسي'),
        ),
    ]
