# Generated by Django 4.1.1 on 2023-02-13 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0028_moneydeleting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField(default=1, verbose_name='رقم المستوى')),
                ('content', models.CharField(max_length=1023, verbose_name='المحتوى')),
            ],
            options={
                'verbose_name': 'مستوى',
                'verbose_name_plural': 'المستويات',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=511, verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'اختصاص',
                'verbose_name_plural': 'الاختصاصات',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_start', models.IntegerField(verbose_name='بداية القسم')),
                ('part_end', models.IntegerField(verbose_name='نهاية القسم')),
                ('part_number', models.IntegerField(default=1, verbose_name='ترتيب القسم')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specializations.level', verbose_name='المستوى')),
                ('students', models.ManyToManyField(blank=True, to='main_app.student', verbose_name='الطلاب الذين أنهوا القسم')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'أقسام',
            },
        ),
        migrations.AddField(
            model_name='level',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specializations.specialization', verbose_name='الاختصاص'),
        ),
    ]
