# Generated by Django 4.2.6 on 2023-10-18 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specializations', '0002_specializationmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name': 'مقرر', 'verbose_name_plural': 'المقررات'},
        ),
        migrations.RenameField(
            model_name='specializationmessage',
            old_name='master_name',
            new_name='master',
        ),
        migrations.RemoveField(
            model_name='level',
            name='level_number',
        ),
        migrations.RemoveField(
            model_name='part',
            name='part_end',
        ),
        migrations.RemoveField(
            model_name='part',
            name='part_start',
        ),
        migrations.AddField(
            model_name='level',
            name='level_name',
            field=models.CharField(default='', max_length=255, verbose_name='اسم المقرر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='part_content',
            field=models.CharField(default='', max_length=255, verbose_name='محتوى القسم'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='part',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specializations.level', verbose_name='المقرر'),
        ),
    ]
